### PR TITLE
fix reversal

### PR DESCRIPTION
**Pull request by sapiderman**
# Hello, Merge/Pull Request (PR)  

## PR type  

- [x] bugfix

### what issue this pr address

1. Closes issue #3 
2. When reversal is requested, app crashes

### how did you implement

1. Fixed accessing error.Error() when err = nil.
2. Provide mising creator context when creating journal

### how do you test

1. create a new journal
2. reversse the above journal
3. should successfully reverse without panic

### CODE REVIEW

**Review by dennypradipta — APPROVED** [review]
Kinda confused at first while checking err and journal equals to nil, but lgtm

**Review by bagusilhami — APPROVED** [review]
ntaps, gan

**Review by newm4n — APPROVED** [review]
Yup logic bug... LGTM

**Comment by newm4n** [comment]
> 

Theres possibility where journal not nil but err is nil. Causing panic.
Thats why checking journal and error is separated.

**Pull request merged**
